### PR TITLE
Handle -coverprofile flag

### LINKED ISSUE #346: Custom coverage profile filename not working
I noticed that there's a command-line option named `-coverprofile` which is supposed to take in a string and output a coverage profile to the provided string after the tests are completed.

```
  -coverprofile string
    	Write a coverage profile to the specified file after all tests have passed.
```

I can see this is mentioned here: https://github.com/onsi/ginkgo/blob/master/ginkgo/run_watch_and_build_command_flags.go#L133

However, when I run my tests like such:

```
$ ginkgo -r -coverprofile coverage.txt
```

I don't get the file at `coverage.txt`, I'll end up with multiple `.coverprofile` files.

I also noticed this isn't mentioned in the Ginkgo documentations, so is this just a feature that was never implemented?

### PR DESCRIPTION
**Pull request by AlexeySoshin**
Fixes #346

### CODE REVIEW

File: ginkgo/testrunner/test_runner.go [hunk 1]
```diff
@@ -473,7 +489,7 @@ func (t *TestRunner) run(cmd *exec.Cmd, completions chan RunResult) RunResult {
 func (t *TestRunner) combineCoverprofiles() {
 	profiles := []string{}
 	for cpu := 1; cpu <= t.numCPU; cpu++ {
-		coverFile := fmt.Sprintf("%s.coverprofile.%d", t.Suite.PackageName, cpu)
+		coverFile := fmt.Sprintf("%s%s.%d", t.Suite.PackageName, CoverProfileSuffix, cpu)
```
Comment (AlexeySoshin) [inline ginkgo/testrunner/test_runner.go]: I'm on it :)

Comment (AlexeySoshin) [inline ginkgo/testrunner/test_runner.go]: @onsi Done

**Comment by onsi** [comment]
sweet!  LGTM!
