### PR TITLE
Make generated Junit file compatable with "Maven Surefire"

### LINKED ISSUE #486: junit.xml generate by JUnitReporter does not compatible with the jenkins "xUnit" plugin
junit.xml that generated by JUnitReported
```xml
<?xml version="1.0" encoding="UTF-8"?>
  <testsuite tests="6" failures="0" time="502.436823874">
      <testcase name="CloudInit UserData A new VirtualMachineInstance with cloudInitNoCloud userDataBase64 source should have cloud-init data" classname="Tests Suite" time="0">
          <skipped></skipped>
      </testcase>
      <testcase name="CloudInit UserData A new VirtualMachineInstance with cloudInitNoCloud userDataBase64 source with injected ssh-key should have ssh-key under authorized keys" classname="Tests Suite" time="0">
          <skipped></skipped>
      </testcase>
      <testcase name="CloudInit UserData A new VirtualMachineInstance with cloudInitNoCloud userData source should process provided cloud-init data" classname="Tests Suite" time="0">
          <skipped></skipped>
      </testcase>
      <testcase name="Windows VirtualMachineInstance should succeed to start a vmi" classname="Tests Suite" time="19.49894934"></testcase>
      <testcase name="Windows VirtualMachineInstance should succeed to stop a running vmi" classname="Tests Suite" time="17.266661977"></testcase>
      <testcase name="Windows VirtualMachineInstance with winrm connection should have correct UUID" classname="Tests Suite" time="220.181473962"></testcase>
      <testcase name="Windows VirtualMachineInstance with winrm connection should have pod IP" classname="Tests Suite" time="185.52644888"></testcase>
      <testcase name="Windows VirtualMachineInstance with kubectl command should succeed to start a vmi" classname="Tests Suite" time="20.747579842"></testcase>
      <testcase name="Windows VirtualMachineInstance with kubectl command should succeed to stop a vmi" classname="Tests Suite" time="27.790455973"></testcase>
  </testsuite>
```
errors that I receive when `xUnit` plugin tries to parse it
```
WARNING: The file '.../junit.xml' is an invalid file.
WARNING: At line 2 of file:.../junit.xml:cvc-pattern-valid: Value '502.436823874' is not facet-valid with respect to pattern '(([0-9]{0,3},)*[0-9]{3}|[0-9]{0,3})*(\.[0-9]{0,3})?' for type '#AnonType_timetestsuite'.
WARNING: At line 2 of file:.../junit.xml:cvc-attribute.3: The value '502.436823874' of attribute 'time' on element 'testsuite' is not valid with respect to its type, 'null'.
WARNING: At line 2 of file:.../junit.xml:cvc-complex-type.4: Attribute 'name' must appear on element 'testsuite'.
WARNING: At line 2 of file:.../junit.xml:cvc-complex-type.4: Attribute 'errors' must appear on element 'testsuite'.
ERROR: The result file '.../junit.xml' for the metric 'JUnit' is not valid. The result file has been skipped.
```

### PR DESCRIPTION
**Pull request by cynepco3hahue**
- add errors attribute to `testsuite`, currently, I will set 0,
but I think Ginkgo must report failures under setup and teardown
methods as errors and not as failures
- cut `testsuite` timestamp to three digits after the dot

Fixes #486 

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@nodo Can you please take a look?

**Comment by williammartin** [comment]
Looks like `math.Round` only exists in Go 1.10

**Comment by cynepco3hahue** [comment]
@williammartin Thanks, missed this `reporters/junit_reporter.go:124:24: undefined: math.Round`, I can do it with `fmt` and `strcov` just wanted to avoid double conversion

File: reporters/junit_reporter.go [hunk 1]
```diff
@@ -119,8 +121,9 @@ func (reporter *JUnitReporter) SpecDidComplete(specSummary *types.SpecSummary) {
 
 func (reporter *JUnitReporter) SpecSuiteDidEnd(summary *types.SuiteSummary) {
 	reporter.suite.Tests = summary.NumberOfSpecsThatWillBeRun
-	reporter.suite.Time = summary.RunTime.Seconds()
+	reporter.suite.Time, _ = strconv.ParseFloat(fmt.Sprintf("%.3f", summary.RunTime.Seconds()), 3)
```
Comment (nodo) [inline reporters/junit_reporter.go]: Do you think we could use `math.Trunc(x * 1000) / 1000` instead?

**Comment by nodo** [comment]
@williammartin @cynepco3hahue just added a minor comment. It feels a bit easier to read. WDYT?

**Comment by cynepco3hahue** [comment]
@nodo I think it is totally fine, I just afraid to use `math` methods after my first commit :smile:

**Comment by nodo** [comment]
@cynepco3hahue the change LGTM, thanks!

One more thing, please could you add a unit test for the change?

**Comment by cynepco3hahue** [comment]
@nodo Done

**Comment by nodo** [comment]
Awesome, merging!

Thanks for your contribution @cynepco3hahue !

**Comment by cynepco3hahue** [comment]
Glad to contribute :smile:

File: reporters/junit_reporter.go [hunk 2]
```diff
@@ -119,8 +121,9 @@ func (reporter *JUnitReporter) SpecDidComplete(specSummary *types.SpecSummary) {
 
 func (reporter *JUnitReporter) SpecSuiteDidEnd(summary *types.SuiteSummary) {
 	reporter.suite.Tests = summary.NumberOfSpecsThatWillBeRun
-	reporter.suite.Time = summary.RunTime.Seconds()
+	reporter.suite.Time = math.Trunc(summary.RunTime.Seconds() * 1000 / 1000)
```
Comment (pohly) [inline reporters/junit_reporter.go]: The commit message says "cut testsuite timestamp to three digits after the dot", but does this code really do that? The multiplication + division don't change the value, and then `math.Trunc` just throws away all sub-second digits.

Perhaps you meant this:
`math.Trunc(summary.RunTime.Seconds() * 1000) / 1000`

Comment (nodo) [reply reporters/junit_reporter.go]: Thank you so much for spotting that @pohly, you are absolutely right. I have opened a PR here https://github.com/onsi/ginkgo/pull/521. What do you think?
